### ISSUE TITLE
development: Unhandled rejection Error: The server does not support SSL connections

### ISSUE THREAD

**Issue by guidorice** [developmentseed/osm-teams#136]
When following the Readme steps for creating a local dev environment, this step threw a Postgresql connection error:

`docker-compose -f docker-compose.dev.yml up`

```
teams_1  |
teams_1  | > osm-teams@0.0.0 dev /usr/src/app
teams_1  | > NODE_ENV=development nodemon --watch app app/index.js
teams_1  |
teams_1  | [nodemon] 1.19.1
teams_1  | [nodemon] to restart at any time, enter `rs`
teams_1  | [nodemon] watching: /usr/src/app/app/**/*
teams_1  | [nodemon] starting `node app/index.js`
teams_1  | Unhandled rejection Error: The server does not support SSL connections
teams_1  |     at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:88:35)
teams_1  |     at Object.onceWrapper (events.js:315:30)
teams_1  |     at emitOne (events.js:116:13)
teams_1  |     at Socket.emit (events.js:211:7)
teams_1  |     at addChunk (_stream_readable.js:263:12)
teams_1  |     at readableAddChunk (_stream_readable.js:250:11)
teams_1  |     at Socket.Readable.push (_stream_readable.js:208:10)
teams_1  |     at TCP.onread (net.js:601:20)
```

**Comment by guidorice** [comment]
A workaround which @kamicut knew of is to add environment variable `PGSSLMODE=disable` to the npm/yarn start script:

` "dev": "NODE_ENV=development nodemon --watch app app/index.js",`
becomes
`"dev": "PGSSLMODE=disable NODE_ENV=development nodemon --watch app app/index.js",`

However this is not an optimal solution. The setting and parsing of SSL/TLS settings in Knex has been discussed a lot here, involving various hacks and workarounds.

https://github.com/knex/knex/issues/852

The preferred method seems to be be to use a parameter on the connection string e.g.

`postgres://postgres@localhost/osm-teams?ssl=false`

Knex added support for this in late 2019 https://github.com/knex/knex/pull/3410
and we can upgrade to Knex 0.20.x to get that.

**Comment by guidorice** [comment]
This is somewhat complicated by the url parameter parsing being implemented in `pg-connection-string` and the `pg` package does not yet implement the new version of `pg-connection-string`

https://github.com/brianc/node-postgres/issues/1689
