### ISSUE TITLE
500 server error on 1st load of front-end (TypeError: Cannot read property 'user' of undefined)

### ISSUE THREAD

**Issue by guidorice** [developmentseed/osm-teams#156]
Often after I have rebuilt osm-teams like

```
docker-compose build
docker-compose -f docker-compose.dev.yml up
```

When I load the front end at https://localhost:8989/ then it displays a JSON formatted 500 server error. Reloading the web app seems to always clear this error.

When the error occurs the docker log says:

```
teams_1  | [nodemon] starting `node app/index.js`
teams_1  | Starting server on port 8989
teams_1  | error TypeError: Cannot read property 'user' of undefined
teams_1  |     at router.get (/usr/src/app/app/manage/index.js:43:62)
teams_1  |     at handleReturn (/usr/src/app/node_modules/express-promise-router/lib/express-promise-router.js:24:27)
teams_1  |     at /usr/src/app/node_modules/express-promise-router/lib/express-promise-router.js:56:9
teams_1  |     at handleReturn (/usr/src/app/node_modules/express-promise-router/lib/express-promise-router.js:24:27)
teams_1  |     at /usr/src/app/node_modules/express-promise-router/lib/express-promise-router.js:56:9
teams_1  |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
teams_1  |     at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
teams_1  |     at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
teams_1  |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
teams_1  |     at /usr/src/app/node_modules/express/lib/router/index.js:281:22
teams_1  |     at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
teams_1  |     at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
teams_1  |     at /usr/src/app/app/manage/sessions.js:62:5
teams_1  |     at handleReturn (/usr/src/app/node_modules/express-promise-router/lib/express-promise-router.js:24:27)
teams_1  |     at /usr/src/app/node_modules/express-promise-router/lib/express-promise-router.js:56:9
teams_1  |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
teams_1  |     at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
teams_1  |     at /usr/src/app/node_modules/express/lib/router/index.js:284:7
teams_1  |     at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
teams_1  |     at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
teams_1  |     at /usr/src/app/node_modules/express-session/index.js:495:7
teams_1  |     at tryCatcher (/usr/src/app/node_modules/knex/node_modules/bluebird/js/release/util.js:16:23)
```

**Comment by vgeorge** [comment]
This error was (probably) fixed by the next-auth refactor and is not present in the development branch.
