### ISSUE TITLE
Silent failure on form post error / no form validation

### ISSUE THREAD

**Issue by guidorice** [developmentseed/osm-teams#161]
Go to http://localhost:8989/teams/create

- Enter for the description:

   > Proin eget dolor in dui congue volutpat et at erat. Curabitur nec ex vitae ante consectetur luctus eget eget dolor. Fusce luctus quam blandit arcu congue, eu dictum tortor tempor. Donec rhoncus purus lacus, sit amet aliquam neque congue eu. Morbi consequat in augue a suscipit. Donec tempor ullamcorper lorem vitae blandit. Pellentesque massa lacus, molestie vel tristique nec, auctor consectetur mi. Cras id lacinia est.

- Hit submit

- It silently fails. the UI should do two things 1) do client-side form validation for all the form fielsd 2) detect the server error (http 400 in this case) display an error dialog showing went wrong.

The docker log has:

```
{ error: value too long for type character varying(255)
teams_1  |     at Connection.parseE (/usr/src/app/node_modules/pg/lib/connection.js:602:11)
teams_1  |     at Connection.parseMessage (/usr/src/app/node_modules/pg/lib/connection.js:399:19)
teams_1  |     at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:121:22)
teams_1  |     at emitOne (events.js:116:13)
teams_1  |     at Socket.emit (events.js:211:7)
teams_1  |     at addChunk (_stream_readable.js:263:12)
teams_1  |     at readableAddChunk (_stream_readable.js:250:11)
teams_1  |     at Socket.Readable.push (_stream_readable.js:208:10)
teams_1  |     at TCP.onread (net.js:601:20)
...
``

**Comment by vgeorge** [comment]
Adding error/success toasts (see https://github.com/developmentseed/osm-teams/issues/49) should help fix this.
