### ISSUE TITLE
Authentication issues in local development - login throws Response Error: 400 bad request

### ISSUE THREAD

**Issue by LanesGood** [developmentseed/osm-teams#193]
I'm able to load localhost:8989 and see "login via OSM" at /login. However, I've hit the following error in the browser once logging in: `http://localhost:8989/login/accept?error=request_forbidden&error_description=The+request+is+not+allowed&error_hint=You+are+not+allowed+to+perform+this+action.&state=WoDRJtMFPcgtSuXyPBtsjVsh`

<details>

<summary>The full error from the command line</summary>

```
hydra_1  | time="2020-10-27T19:35:16Z" level=info msg="completed handling request" measure#hydra/public: http://localhost:4444/.latency=6320500 method=GET remote="172.21.0.1:36516" request="/oauth2/auth?client_id=manage&login_verifier=b226f3047e4e40559ea71248a949cfb1&redirect_uri=http%3A%2F%2Flocalhost%3A8989%2Flogin%2Faccept&response_type=code&scope=openid+clients&state=WoDRJtMFPcgtSuXyPBtsjVsh" status=302 text_status=Found took=6.3205ms
hydra_1  | time="2020-10-27T19:35:16Z" level=info msg="started handling request" method=POST remote="172.21.0.3:45230" request=/oauth2/token
hydra_1  | time="2020-10-27T19:35:16Z" level=error msg="An error occurred" debug=": not_found" description="The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client" error=invalid_grant
hydra_1  | time="2020-10-27T19:35:16Z" level=info msg="completed handling request" measure#hydra/public: http://localhost:4444/.latency=79005200 method=POST remote="172.21.0.3:45230" request=/oauth2/token status=400 text_status="Bad Request" took=79.0052ms
teams_1  | Error: Response Error: 400 Bad Request
teams_1  |     at internals.Client._shortcut (/usr/src/app/node_modules/wreck/lib/index.js:635:11)
teams_1  |     at runMicrotasks (<anonymous>)
teams_1  |     at processTicksAndRejections (internal/process/task_queues.js:97:5)
teams_1  |     at async Object.request (/usr/src/app/node_modules/simple-oauth2/lib/core.js:64:20)
teams_1  |     at async loginAccept (/usr/src/app/app/manage/login.js:62:22) {
teams_1  |   data: {
teams_1  |     isResponseError: true,
teams_1  |     headers: {
teams_1  |       'content-type': 'application/json;charset=UTF-8',
teams_1  |       date: 'Tue, 27 Oct 2020 19:35:16 GMT',
teams_1  |       'content-length': '302',
teams_1  |       connection: 'close'
teams_1  |     },
teams_1  |     res: IncomingMessage {
teams_1  |       _readableState: [ReadableState],
teams_1  |       readable: false,
teams_1  |       _events: [Object: null prototype],
teams_1  |       _eventsCount: 2,
teams_1  |       _maxListeners: undefined,
teams_1  |       socket: [Socket],
teams_1  |       connection: [Socket],
teams_1  |       httpVersionMajor: 1,
teams_1  |       httpVersionMinor: 1,
teams_1  |       httpVersion: '1.1',
teams_1  |       complete: true,
teams_1  |       headers: [Object],
teams_1  |       rawHeaders: [Array],
teams_1  |       trailers: {},
teams_1  |       rawTrailers: [],
teams_1  |       aborted: false,
teams_1  |       upgrade: false,
teams_1  |       url: '',
teams_1  |       method: null,
teams_1  |       statusCode: 400,
teams_1  |       statusMessage: 'Bad Request',
teams_1  |       client: [Socket],
teams_1  |       _consuming: false,
teams_1  |       _dumped: false,
teams_1  |       req: [ClientRequest],
teams_1  |       [Symbol(kCapture)]: false
teams_1  |     },
teams_1  |     payload: {
teams_1  |       error: 'invalid_grant',
teams_1  |       error_description: 'The provided authorization grant (e.g., authorization code, resource owner credentials) or refresh token is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client',
teams_1  |       status_code: 400
teams_1  |     }
teams_1  |   },
teams_1  |   isBoom: true,
teams_1  |   isServer: false,
teams_1  |   output: {
teams_1  |     statusCode: 400,
teams_1  |     payload: {
teams_1  |       statusCode: 400,
teams_1  |       error: 'Bad Request',
teams_1  |       message: 'Response Error: 400 Bad Request'
teams_1  |     },
teams_1  |     headers: {}
teams_1  |   },
teams_1  |   reformat: [Function],
teams_1  |   typeof: [Function]
teams_1  | }
```
</details>

I also saw the below error when setting up the "first-party" app via the osm-teams readme instructions. I have the hydra and teams containers successfully running in one terminal tab, and see the below output in the second tab. I'm unclear whether I should be entering any variables in the subsequent lines with a `\`:
<details>

<summary>View error</summary>

```
~/github/osm-teams $ docker-compose exec hydra hydra clients create --endpoint http://localhost:4445 \
>   --id manage \
>   --secret manage-secret \
>   --response-types code,id_token \
>   --grant-types refresh_token,authorization_code \
>   --scope openid,offline,clients \
>   --callbacks http://localhost:8989/login/accept
Config file not found because "Config File ".hydra" Not Found in "[/]""
You should not provide secrets using command line flags, the secret might leak to bash history and similar systems
OAuth 2.0 Client ID: manage
~/github/osm-teams $ 
```

</details>

Lastly, I'm also unsure if I'm entering the correct information in the OSM oauth app creation process. I've tried using both `http://localhost:8989` and `http://localhost:8989/login` for the "Main Application URL." Is a Callback URL also required? What would this be? We should include in the documentation if so.

Appreciate any insights or quick fixes cc/@necoline @jvntf @kamicut

**Comment by LanesGood** [comment]
Noting that I hit this same issue when I log in via a third party app.

**Comment by LanesGood** [comment]
This issue is not present since switching to V2. I do experience issues in Chrome, but believe this is a different issue
